// <auto-generated />
using System;
using Marina.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Marina.DataAccess.Migrations
{
    [DbContext(typeof(MarinaDbContext))]
    [Migration("20240718061616_UpdateCustomerSeedData")]
    partial class UpdateCustomerSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Marina.Models.Dock", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("ElectricalService")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("WaterService")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Dock");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ElectricalService = true,
                            Name = "Dock A",
                            WaterService = true
                        },
                        new
                        {
                            ID = 2,
                            ElectricalService = false,
                            Name = "Dock B",
                            WaterService = true
                        },
                        new
                        {
                            ID = 3,
                            ElectricalService = true,
                            Name = "Dock C",
                            WaterService = false
                        });
                });

            modelBuilder.Entity("Marina.Models.Lease", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SlipId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("SlipId");

                    b.ToTable("Leases");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CustomerID = "user1_id",
                            SlipId = 20
                        },
                        new
                        {
                            ID = 2,
                            CustomerID = "user2_id",
                            SlipId = 42
                        },
                        new
                        {
                            ID = 3,
                            CustomerID = "user3_id",
                            SlipId = 88
                        });
                });

            modelBuilder.Entity("Marina.Models.Slip", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DockId")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DockId");

                    b.ToTable("Slips");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DockId = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            ID = 2,
                            DockId = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            ID = 3,
                            DockId = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            ID = 4,
                            DockId = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            ID = 5,
                            DockId = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            ID = 6,
                            DockId = 1,
                            Length = 16,
                            Width = 8
                        },
                        new
                        {
                            ID = 7,
                            DockId = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            ID = 8,
                            DockId = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            ID = 9,
                            DockId = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            ID = 10,
                            DockId = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            ID = 11,
                            DockId = 1,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            ID = 12,
                            DockId = 1,
                            Length = 22,
                            Width = 8
                        },
                        new
                        {
                            ID = 13,
                            DockId = 1,
                            Length = 22,
                            Width = 8
                        },
                        new
                        {
                            ID = 14,
                            DockId = 1,
                            Length = 22,
                            Width = 8
                        },
                        new
                        {
                            ID = 15,
                            DockId = 1,
                            Length = 22,
                            Width = 8
                        },
                        new
                        {
                            ID = 16,
                            DockId = 1,
                            Length = 24,
                            Width = 8
                        },
                        new
                        {
                            ID = 17,
                            DockId = 1,
                            Length = 24,
                            Width = 8
                        },
                        new
                        {
                            ID = 18,
                            DockId = 1,
                            Length = 24,
                            Width = 8
                        },
                        new
                        {
                            ID = 19,
                            DockId = 1,
                            Length = 24,
                            Width = 8
                        },
                        new
                        {
                            ID = 20,
                            DockId = 1,
                            Length = 26,
                            Width = 8
                        },
                        new
                        {
                            ID = 21,
                            DockId = 1,
                            Length = 26,
                            Width = 8
                        },
                        new
                        {
                            ID = 22,
                            DockId = 1,
                            Length = 26,
                            Width = 8
                        },
                        new
                        {
                            ID = 23,
                            DockId = 1,
                            Length = 26,
                            Width = 8
                        },
                        new
                        {
                            ID = 24,
                            DockId = 1,
                            Length = 26,
                            Width = 8
                        },
                        new
                        {
                            ID = 25,
                            DockId = 1,
                            Length = 26,
                            Width = 8
                        },
                        new
                        {
                            ID = 26,
                            DockId = 1,
                            Length = 28,
                            Width = 8
                        },
                        new
                        {
                            ID = 27,
                            DockId = 1,
                            Length = 28,
                            Width = 8
                        },
                        new
                        {
                            ID = 28,
                            DockId = 1,
                            Length = 28,
                            Width = 8
                        },
                        new
                        {
                            ID = 29,
                            DockId = 1,
                            Length = 28,
                            Width = 8
                        },
                        new
                        {
                            ID = 30,
                            DockId = 1,
                            Length = 28,
                            Width = 8
                        },
                        new
                        {
                            ID = 31,
                            DockId = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            ID = 32,
                            DockId = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            ID = 33,
                            DockId = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            ID = 34,
                            DockId = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            ID = 35,
                            DockId = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            ID = 36,
                            DockId = 2,
                            Length = 18,
                            Width = 8
                        },
                        new
                        {
                            ID = 37,
                            DockId = 2,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            ID = 38,
                            DockId = 2,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            ID = 39,
                            DockId = 2,
                            Length = 20,
                            Width = 8
                        },
                        new
                        {
                            ID = 40,
                            DockId = 2,
                            Length = 22,
                            Width = 8
                        },
                        new
                        {
                            ID = 41,
                            DockId = 2,
                            Length = 22,
                            Width = 8
                        },
                        new
                        {
                            ID = 42,
                            DockId = 2,
                            Length = 22,
                            Width = 8
                        },
                        new
                        {
                            ID = 43,
                            DockId = 2,
                            Length = 24,
                            Width = 8
                        },
                        new
                        {
                            ID = 44,
                            DockId = 2,
                            Length = 24,
                            Width = 8
                        },
                        new
                        {
                            ID = 45,
                            DockId = 2,
                            Length = 24,
                            Width = 8
                        },
                        new
                        {
                            ID = 46,
                            DockId = 2,
                            Length = 24,
                            Width = 8
                        },
                        new
                        {
                            ID = 47,
                            DockId = 2,
                            Length = 28,
                            Width = 8
                        },
                        new
                        {
                            ID = 48,
                            DockId = 2,
                            Length = 28,
                            Width = 8
                        },
                        new
                        {
                            ID = 49,
                            DockId = 2,
                            Length = 28,
                            Width = 8
                        },
                        new
                        {
                            ID = 50,
                            DockId = 2,
                            Length = 30,
                            Width = 8
                        },
                        new
                        {
                            ID = 51,
                            DockId = 2,
                            Length = 30,
                            Width = 8
                        },
                        new
                        {
                            ID = 52,
                            DockId = 2,
                            Length = 30,
                            Width = 8
                        },
                        new
                        {
                            ID = 53,
                            DockId = 2,
                            Length = 30,
                            Width = 8
                        },
                        new
                        {
                            ID = 54,
                            DockId = 2,
                            Length = 30,
                            Width = 8
                        },
                        new
                        {
                            ID = 55,
                            DockId = 2,
                            Length = 32,
                            Width = 8
                        },
                        new
                        {
                            ID = 56,
                            DockId = 2,
                            Length = 32,
                            Width = 8
                        },
                        new
                        {
                            ID = 57,
                            DockId = 2,
                            Length = 32,
                            Width = 8
                        },
                        new
                        {
                            ID = 58,
                            DockId = 2,
                            Length = 32,
                            Width = 8
                        },
                        new
                        {
                            ID = 59,
                            DockId = 2,
                            Length = 32,
                            Width = 8
                        },
                        new
                        {
                            ID = 60,
                            DockId = 2,
                            Length = 32,
                            Width = 8
                        },
                        new
                        {
                            ID = 61,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 62,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 63,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 64,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 65,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 66,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 67,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 68,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 69,
                            DockId = 3,
                            Length = 22,
                            Width = 10
                        },
                        new
                        {
                            ID = 70,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            ID = 71,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            ID = 72,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            ID = 73,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            ID = 74,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            ID = 75,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            ID = 76,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            ID = 77,
                            DockId = 3,
                            Length = 24,
                            Width = 10
                        },
                        new
                        {
                            ID = 78,
                            DockId = 3,
                            Length = 28,
                            Width = 12
                        },
                        new
                        {
                            ID = 79,
                            DockId = 3,
                            Length = 28,
                            Width = 12
                        },
                        new
                        {
                            ID = 80,
                            DockId = 3,
                            Length = 28,
                            Width = 12
                        },
                        new
                        {
                            ID = 81,
                            DockId = 3,
                            Length = 28,
                            Width = 12
                        },
                        new
                        {
                            ID = 82,
                            DockId = 3,
                            Length = 28,
                            Width = 12
                        },
                        new
                        {
                            ID = 83,
                            DockId = 3,
                            Length = 28,
                            Width = 12
                        },
                        new
                        {
                            ID = 84,
                            DockId = 3,
                            Length = 28,
                            Width = 12
                        },
                        new
                        {
                            ID = 85,
                            DockId = 3,
                            Length = 28,
                            Width = 12
                        },
                        new
                        {
                            ID = 86,
                            DockId = 3,
                            Length = 32,
                            Width = 12
                        },
                        new
                        {
                            ID = 87,
                            DockId = 3,
                            Length = 32,
                            Width = 12
                        },
                        new
                        {
                            ID = 88,
                            DockId = 3,
                            Length = 32,
                            Width = 12
                        },
                        new
                        {
                            ID = 89,
                            DockId = 3,
                            Length = 32,
                            Width = 12
                        },
                        new
                        {
                            ID = 90,
                            DockId = 3,
                            Length = 32,
                            Width = 12
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = "user1_id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cf10f34b-16c6-41a9-9251-8dee5f117e18",
                            Email = "john.doe@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.DOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHN.DOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMwNYnJc214ESi3B9hxvqdWa7+rj2kz+AKvs4co+lYUhHz6ldcWT/jjaGR7ZkmTpnA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d6148509-7ebb-4ed8-95f6-8f1c04b315c8",
                            TwoFactorEnabled = false,
                            UserName = "john.doe@example.com"
                        },
                        new
                        {
                            Id = "user2_id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "768a0f30-ab21-478e-aeee-118f424b064a",
                            Email = "sara.williams@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA.WILLIAMS@EXAMPLE.COM",
                            NormalizedUserName = "SARA.WILLIAMS@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEB7aQQtV+rvIkw4P+uFwALcMYPdhtyL09au9Zth0IZcdT9et5Y6E+0aByO/u/nGdmw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a555672f-0da7-4b89-bc7e-5d5b29804531",
                            TwoFactorEnabled = false,
                            UserName = "sara.williams@example.com"
                        },
                        new
                        {
                            Id = "user3_id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "353a061b-7e73-424b-9c71-f73615271df8",
                            Email = "ken.wong@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KEN.WONG@EXAMPLE.COM",
                            NormalizedUserName = "KEN.WONG@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPpd4Upb7UjG4ju/0YgJAchOQvc/ATNFsnYHcZkuRCQpw70gDKqUktZ0FkFEjVdJ7w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5cb95729-f3c3-43a2-82ef-c39e77a2b203",
                            TwoFactorEnabled = false,
                            UserName = "ken.wong@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Marina.Models.Customer", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("Marina.Models.Lease", b =>
                {
                    b.HasOne("Marina.Models.Customer", "Customer")
                        .WithMany("Leases")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marina.Models.Slip", "Slip")
                        .WithMany("Leases")
                        .HasForeignKey("SlipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Slip");
                });

            modelBuilder.Entity("Marina.Models.Slip", b =>
                {
                    b.HasOne("Marina.Models.Dock", "Dock")
                        .WithMany("Slips")
                        .HasForeignKey("DockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dock");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marina.Models.Dock", b =>
                {
                    b.Navigation("Slips");
                });

            modelBuilder.Entity("Marina.Models.Slip", b =>
                {
                    b.Navigation("Leases");
                });

            modelBuilder.Entity("Marina.Models.Customer", b =>
                {
                    b.Navigation("Leases");
                });
#pragma warning restore 612, 618
        }
    }
}
